/* =====================================================
NAVIDROME MUSIC WIDGET
===================================================== */
(function () {
  const ND_CONFIG = {
    baseUrl: "http://YOUR_LOCAL_IP:PORT",
    fallbackUrl: "https://YOUR_TUNNEL_URL", // or null if not using a tunnel
    activeUrl: null,
    user: "Artyom",
    token: "YOUR_TOKEN_KEY_HERE", // The token is generated by taking the MD5 hash of your password combined with that salt — for example in a terminal: echo -n "yourpasswordabc123" | md5sum.
    salt: "YOUR_SALT_KEY", // The salt is a random string you create yourself (e.g. abc123), and the token is generated by taking the MD5 hash of your password combined with that salt — for example in a terminal: echo -n "yourpasswordabc123" | md5sum.
    version: "1.16.1",
    client: "homepage",
    groupName: "NAVIDROME-LIBRARY",
    pollMs: 120 * 1000,
    listSize: 20,
    debug: false
  };

  function log(...args) {
    if (ND_CONFIG.debug) console.log("[Homepage Navidrome]", ...args);
  }

  function normalizeText(v) {
    return (v || "").replace(/\s+/g, " ").trim();
  }

  function escapeHtml(str = "") {
    return String(str)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;")
      .replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  }

  function fmtDuration(secs) {
    if (!secs) return "";
    const m = Math.floor(secs / 60);
    const s = Math.floor(secs % 60);
    return `${m}:${String(s).padStart(2, "0")}`;
  }

  function fmtDate(str) {
    if (!str) return "";
    try {
      return new Date(str).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
    } catch (_) { return ""; }
  }

  function apiParams(extra = {}) {
    const base = {
      u: ND_CONFIG.user,
      t: ND_CONFIG.token,
      s: ND_CONFIG.salt,
      v: ND_CONFIG.version,
      c: ND_CONFIG.client,
      f: "json"
    };
    return new URLSearchParams({ ...base, ...extra }).toString();
  }

  function apiUrl(endpoint, extra = {}) {
    const base = ND_CONFIG.activeUrl || ND_CONFIG.baseUrl;
    return `${base}/rest/${endpoint}.view?${apiParams(extra)}`;
  }

  function coverUrl(id, size = 200) {
    if (!id) return null;
    const base = ND_CONFIG.activeUrl || ND_CONFIG.baseUrl;
    return `${base}/rest/getCoverArt.view?${apiParams({ id, size })}`;
  }

  async function apiFetch(endpoint, extra = {}) {
    const candidates = [];
    if (ND_CONFIG.activeUrl) candidates.push(ND_CONFIG.activeUrl);
    if (!candidates.includes(ND_CONFIG.baseUrl)) candidates.push(ND_CONFIG.baseUrl);
    if (ND_CONFIG.fallbackUrl && !candidates.includes(ND_CONFIG.fallbackUrl)) candidates.push(ND_CONFIG.fallbackUrl);

    let lastErr = null;
    for (const base of candidates) {
      try {
        const url = `${base}/rest/${endpoint}.view?${apiParams(extra)}`;
        const res = await fetch(url, { signal: (() => { const c = new AbortController(); setTimeout(() => c.abort(), 8000); return c.signal; })() });
        if (!res.ok) throw new Error(`Navidrome ${res.status}`);
        const data = await res.json();
        const r = data["subsonic-response"];
        if (!r || r.status !== "ok") throw new Error(r?.error?.message || "API error");
        ND_CONFIG.activeUrl = base;
        return r;
      } catch (err) {
        lastErr = err;
      }
    }
    throw lastErr || new Error("All URLs failed for Navidrome");
  }

  // ── Group finder ──────────────────────────────────
  function findGroupContainer() {
    const headings = Array.from(document.querySelectorAll("h2, h3, .group-title, .service-group-name"));
    const heading = headings.find(el => normalizeText(el.textContent) === ND_CONFIG.groupName);
    if (!heading) { log("Group not found yet"); return null; }
    return heading.closest("section") || heading.closest("div[class*='group']") ||
      heading.parentElement?.parentElement || heading.parentElement;
  }

  function ensureHost(group) {
    let host = group.querySelector(".nd-widget-host");
    if (host) return host;
    host = document.createElement("div");
    host.className = "nd-widget-host";
    group.appendChild(host);
    return host;
  }

  // ── Card builders ─────────────────────────────────
  function albumCard(item, index) {
    const cover = coverUrl(item.coverArt);
    const name = escapeHtml(item.name || item.album || item.title || "Unknown");
    const artist = escapeHtml(item.artist || item.albumArtist || "");
    const year = item.year ? `${item.year}` : "";
    const plays = item.playCount ? `${item.playCount.toLocaleString()} plays` : "";
    const sub = [artist, year, plays].filter(Boolean).join(" · ");
    const href = `${ND_CONFIG.baseUrl}/app/#/album/${item.id}`;

    return `
      <a class="nd-card" href="${href}" target="_blank" rel="noopener noreferrer"
         style="animation-delay:${index * 35}ms" title="${name}">
        <div class="nd-card-art">
          ${cover
        ? `<img src="${cover}" alt="${name}" loading="lazy" decoding="async">`
        : `<div class="nd-card-placeholder"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/><line x1="12" y1="3" x2="12" y2="9"/></svg></div>`
      }
        </div>
        <div class="nd-card-meta">
          <div class="nd-card-title">${name}</div>
          ${sub ? `<div class="nd-card-sub">${sub}</div>` : ""}
        </div>
      </a>`;
  }

  function songRow(item, index) {
    const cover = coverUrl(item.coverArt || item.albumId, 80);
    const title = escapeHtml(item.title || "Unknown");
    const artist = escapeHtml(item.artist || "");
    const album = escapeHtml(item.album || "");
    const dur = fmtDuration(item.duration);
    const plays = item.playCount ? `${item.playCount.toLocaleString()}×` : "";
    const href = `${ND_CONFIG.baseUrl}/app/#/album/${item.albumId}`;

    return `
      <a class="nd-song-row" href="${href}" target="_blank" rel="noopener noreferrer"
         style="animation-delay:${index * 25}ms">
        <div class="nd-song-art">
          ${cover
        ? `<img src="${cover}" alt="${title}" loading="lazy" decoding="async">`
        : `<div class="nd-song-placeholder"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/></svg></div>`
      }
        </div>
        <div class="nd-song-body">
          <div class="nd-song-title">${title}</div>
          <div class="nd-song-meta">${[artist, album].filter(Boolean).join(" — ")}</div>
        </div>
        <div class="nd-song-right">
          ${plays ? `<span class="nd-song-plays">${plays}</span>` : ""}
          ${dur ? `<span class="nd-song-dur">${dur}</span>` : ""}
        </div>
      </a>`;
  }

  function nowPlayingRow(item, index) {
    const cover = coverUrl(item.coverArt, 80);
    const title = escapeHtml(item.title || "Unknown");
    const artist = escapeHtml(item.artist || "");
    const album = escapeHtml(item.album || "");
    const user = escapeHtml(item.username || "");
    const href = `${ND_CONFIG.baseUrl}/app/#/album/${item.albumId}`;

    return `
      <a class="nd-song-row nd-now-playing-row" href="${href}" target="_blank" rel="noopener noreferrer"
         style="animation-delay:${index * 25}ms">
        <div class="nd-song-art">
          ${cover
        ? `<img src="${cover}" alt="${title}" loading="lazy">`
        : `<div class="nd-song-placeholder"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/></svg></div>`
      }
          <div class="nd-playing-dot"></div>
        </div>
        <div class="nd-song-body">
          <div class="nd-song-title">${title}</div>
          <div class="nd-song-meta">${[artist, album].filter(Boolean).join(" — ")}</div>
        </div>
        <div class="nd-song-right">
          ${user ? `<span class="nd-song-user">${user}</span>` : ""}
          <div class="nd-equalizer" aria-label="Now playing">
            <span></span><span></span><span></span>
          </div>
        </div>
      </a>`;
  }

  function playlistCard(item, index) {
    const cover = coverUrl(item.coverArt);
    const name = escapeHtml(item.name || "Untitled");
    const count = item.songCount ? `${item.songCount} tracks` : "";
    const dur = item.duration ? fmtDuration(item.duration) : "";
    const sub = [count, dur].filter(Boolean).join(" · ");
    const href = `${ND_CONFIG.baseUrl}/app/#/playlist/${item.id}`;

    return `
      <a class="nd-card nd-playlist-card" href="${href}" target="_blank" rel="noopener noreferrer"
         style="animation-delay:${index * 35}ms" title="${name}">
        <div class="nd-card-art nd-card-art--square">
          ${cover
        ? `<img src="${cover}" alt="${name}" loading="lazy">`
        : `<div class="nd-card-placeholder"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg></div>`
      }
        </div>
        <div class="nd-card-meta">
          <div class="nd-card-title">${name}</div>
          ${sub ? `<div class="nd-card-sub">${sub}</div>` : ""}
        </div>
      </a>`;
  }

  // ── Section renderers ─────────────────────────────
  async function renderNowPlaying() {
    const r = await apiFetch("getNowPlaying");
    const items = r.nowPlaying?.entry || [];
    if (!items.length) {
      return `<div class="nd-empty">
        <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/><line x1="12" y1="3" x2="12" y2="9"/></svg>
        <div>Nothing playing right now</div>
      </div>`;
    }
    return `<div class="nd-song-list">${items.map(nowPlayingRow).join("")}</div>`;
  }

  async function renderRecentlyPlayed() {
    const r = await apiFetch("getAlbumList2", { type: "recent", size: ND_CONFIG.listSize });
    const items = r.albumList2?.album || [];
    if (!items.length) return `<div class="nd-empty">No recently played albums</div>`;
    return `<div class="nd-card-grid">${items.map(albumCard).join("")}</div>`;
  }

  async function renderMostPlayed() {
    const r = await apiFetch("getAlbumList2", { type: "frequent", size: ND_CONFIG.listSize });
    const items = r.albumList2?.album || [];
    if (!items.length) return `<div class="nd-empty">No play history yet</div>`;
    return `<div class="nd-card-grid">${items.map(albumCard).join("")}</div>`;
  }

  async function renderNewest() {
    const r = await apiFetch("getAlbumList2", { type: "newest", size: ND_CONFIG.listSize });
    const items = r.albumList2?.album || [];
    if (!items.length) return `<div class="nd-empty">No albums found</div>`;
    return `<div class="nd-card-grid">${items.map(albumCard).join("")}</div>`;
  }

  async function renderStarred() {
    const r = await apiFetch("getStarred2");
    const albums = r.starred2?.album || [];
    const songs = r.starred2?.song || [];
    if (!albums.length && !songs.length) {
      return `<div class="nd-empty">
        <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>
        <div>No starred items yet</div>
      </div>`;
    }
    let html = "";
    if (albums.length) {
      html += `<div class="nd-section-label">Starred Albums</div>
               <div class="nd-card-grid">${albums.map(albumCard).join("")}</div>`;
    }
    if (songs.length) {
      html += `<div class="nd-section-label" style="margin-top:16px;">Starred Tracks</div>
               <div class="nd-song-list">${songs.map(songRow).join("")}</div>`;
    }
    return html;
  }

  async function renderPlaylists() {
    const r = await apiFetch("getPlaylists");
    const items = r.playlists?.playlist || [];
    if (!items.length) return `<div class="nd-empty">No playlists found</div>`;
    return `<div class="nd-card-grid">${items.map(playlistCard).join("")}</div>`;
  }

  async function renderStats() {
    const [artistsR, albumsR, scanR] = await Promise.allSettled([
      apiFetch("getArtists"),
      apiFetch("getAlbumList2", { type: "alphabeticalByName", size: 1 }),
      apiFetch("getScanStatus")
    ]);

    const artists = artistsR.status === "fulfilled"
      ? (artistsR.value.artists?.index || []).reduce((n, idx) => n + (idx.artist?.length || 0), 0)
      : "—";

    const scanning = scanR.status === "fulfilled" ? scanR.value.scanStatus?.scanning : false;
    const lastScan = scanR.status === "fulfilled" ? scanR.value.scanStatus?.lastScan : null;

    // Fetch all album counts via alphabetical list
    const [totalAlbums, totalSongs, recentR] = await Promise.allSettled([
      apiFetch("getAlbumList2", { type: "alphabeticalByName", size: 500 }),
      apiFetch("getRandomSongs", { size: 1 }),
      apiFetch("getAlbumList2", { type: "newest", size: 5 })
    ]);

    const albumList = totalAlbums.status === "fulfilled"
      ? (totalAlbums.value.albumList2?.album || [])
      : [];
    const albumCount = albumList.length || "—";
    const trackCount = albumList.length
      ? albumList.reduce((sum, a) => sum + (a.songCount || 0), 0)
      : "—";

    const recentAlbums = recentR.status === "fulfilled"
      ? (recentR.value.albumList2?.album || [])
      : [];

    return `
      <div class="nd-stats-grid">
        <div class="nd-stat-card">
          <div class="nd-stat-icon">
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>
          </div>
          <div class="nd-stat-num">${typeof artists === "number" ? artists.toLocaleString() : artists}</div>
          <div class="nd-stat-label">Artists</div>
        </div>
        <div class="nd-stat-card">
          <div class="nd-stat-icon">
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="12" cy="12" r="4"/><circle cx="12" cy="12" r="1"/></svg>
          </div>
          <div class="nd-stat-num">${typeof albumCount === "number" ? albumCount.toLocaleString() : albumCount}</div>
          <div class="nd-stat-label">Albums</div>
        </div>
        <div class="nd-stat-card">
          <div class="nd-stat-icon">
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/><line x1="12" y1="3" x2="12" y2="9"/></svg>
          </div>
          <div class="nd-stat-num">${typeof trackCount === "number" ? trackCount.toLocaleString() : trackCount}</div>
          <div class="nd-stat-label">Tracks</div>
        </div>
        <div class="nd-stat-card ${scanning ? "nd-stat-card--scanning" : ""}">
          <div class="nd-stat-icon">
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg>
          </div>
          <div class="nd-stat-num" style="font-size:0.78rem;">${scanning ? "Scanning…" : (lastScan ? fmtDate(lastScan) : "—")}</div>
          <div class="nd-stat-label">Library scan</div>
        </div>
      </div>
      ${recentAlbums.length ? `
        <div class="nd-section-label" style="margin-top:16px;">Recently Added</div>
        <div class="nd-card-grid">${recentAlbums.map(albumCard).join("")}</div>
      ` : ""}`;
  }

  // ── Tab definitions ───────────────────────────────
  const TABS = [
    { key: "stats", label: "Library", icon: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>`, render: renderStats },
    { key: "newest", label: "Newest", icon: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>`, render: renderNewest },
    { key: "nowplaying", label: "Now Playing", icon: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="5 3 19 12 5 21 5 3"/></svg>`, render: renderNowPlaying },
    { key: "recent", label: "Recent", icon: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>`, render: renderRecentlyPlayed },
    { key: "frequent", label: "Top Played", icon: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></svg>`, render: renderMostPlayed },
    { key: "starred", label: "Starred", icon: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>`, render: renderStarred },
    { key: "playlists", label: "Playlists", icon: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>`, render: renderPlaylists },
  ];

  // ── Shell builder ─────────────────────────────────
  function buildShell() {
    const tabs = TABS.map((t, i) => `
    <button class="nd-tab${i === 0 ? " nd-tab--active" : ""}"
            data-tab="${t.key}" type="button" role="tab"
            aria-selected="${i === 0}">
      ${t.icon}
      <span>${t.label}</span>
    </button>`).join("");

    return `
    <div class="nd-shell">
      <div class="nd-header">
        <div class="nd-header-left">
          <img
            src="https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/navidrome.webp"
            alt="Navidrome"
            class="nd-icon"
          />
          <span class="nd-title">Navidrome</span>
        </div>
        <div class="nd-header-right">
          <div class="nd-tabs" role="tablist">${tabs}</div>
          <a class="nd-open-btn" href="${ND_CONFIG.baseUrl}" target="_blank" rel="noopener noreferrer">
            Open
            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>
              <polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/>
            </svg>
          </a>
        </div>
      </div>
      <div class="nd-panel" id="nd-panel">
        <div class="nd-skeleton-wrap">${Array.from({ length: 6 }, () => `<div class="nd-skeleton-row"></div>`).join("")}</div>
      </div>
      <div class="nd-footer" id="nd-footer">Updated ${new Date().toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", second: "2-digit", hour12: true })}</div>
    </div>`;
  }

  // ── Tab switching ─────────────────────────────────
  let _currentTab = "stats";
  let _tabCache = {};

  async function switchTab(shell, key, force = false) {
    if (_currentTab === key && !force) return;
    _currentTab = key;

    shell.querySelectorAll(".nd-tab").forEach(t => {
      const active = t.dataset.tab === key;
      t.classList.toggle("nd-tab--active", active);
      t.setAttribute("aria-selected", String(active));
    });

    const panel = shell.querySelector("#nd-panel");
    const footer = shell.querySelector("#nd-footer");
    if (!panel) return;

    if (_tabCache[key] && !force) {
      panel.innerHTML = _tabCache[key];
      revealCards(panel);
      return;
    }

    panel.innerHTML = `<div class="nd-skeleton-wrap">${Array.from({ length: 5 }, () => `<div class="nd-skeleton-row"></div>`).join("")}</div>`;

    const tab = TABS.find(t => t.key === key);
    if (!tab) return;

    try {
      const html = await tab.render();
      _tabCache[key] = html;
      panel.innerHTML = html;
      revealCards(panel);
      if (footer) footer.textContent = `Updated ${new Date().toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", second: "2-digit", hour12: true })}`;
    } catch (err) {
      console.error("[Homepage Navidrome]", err);
      panel.innerHTML = `
        <div class="nd-error">
          <div class="nd-error-title">Failed to load</div>
          <div class="nd-error-msg">${escapeHtml(err.message)}</div>
        </div>`;
    }
  }

  function revealCards(panel) {
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        panel.querySelectorAll(".nd-card, .nd-song-row").forEach(el => {
          el.style.opacity = "1";
          el.style.transform = "translateY(0)";
        });
      });
    });
  }

  // ── Main render ───────────────────────────────────
  async function renderNavidromeWidget() {
    const group = findGroupContainer();
    if (!group) return;
    if (group.querySelector(".nd-shell")) return;

    const host = ensureHost(group);
    host.innerHTML = buildShell();
    const shell = host.querySelector(".nd-shell");

    shell.querySelectorAll(".nd-tab").forEach(tab => {
      tab.addEventListener("click", () => switchTab(shell, tab.dataset.tab));
    });

    // Force render into this specific shell's panel, not by ID
    const panel = shell.querySelector(".nd-panel");
    const footer = shell.querySelector(".nd-footer");
    if (!panel) return;

    _currentTab = "stats";
    shell.querySelectorAll(".nd-tab").forEach(t => {
      const active = t.dataset.tab === "stats";
      t.classList.toggle("nd-tab--active", active);
      t.setAttribute("aria-selected", String(active));
    });

    try {
      const html = await renderStats();
      _tabCache["stats"] = html;
      panel.innerHTML = html;
      revealCards(panel);
      if (footer) footer.textContent = `Updated ${new Date().toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", second: "2-digit", hour12: true })}`;
    } catch (err) {
      console.error("[Homepage Navidrome]", err);
      panel.innerHTML = `<div class="nd-error"><div class="nd-error-title">Failed to load</div><div class="nd-error-msg">${escapeHtml(err.message)}</div></div>`;
    }
  }

  // ── Poll refresh (clears cache, re-renders active tab) ─
  function startPolling(host) {
    setInterval(async () => {
      _tabCache = {};
      const shell = host.querySelector(".nd-shell");
      if (shell) await switchTab(shell, _currentTab, true);
    }, ND_CONFIG.pollMs);
  }

  let _ndPolling = false;

  function init() {
    const start = () => {
      setTimeout(async () => {
        await renderNavidromeWidget();
        const host = document.querySelector(".nd-widget-host");
        if (host && !_ndPolling) {
          _ndPolling = true;
          startPolling(host);
        }
      }, 800);
    };

    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", start, { once: true });
    } else {
      start();
    }

    let pending = false;
    const observer = new MutationObserver(() => {
      if (pending) return;
      if (document.querySelector(".nd-widget-host .nd-shell")) return;
      pending = true;
      setTimeout(async () => {
        pending = false;
        await renderNavidromeWidget();
        const host = document.querySelector(".nd-widget-host");
        if (host && !_ndPolling) {
          _ndPolling = true;
          startPolling(host);
        }
      }, 300);
    });
    observer.observe(document.body, { childList: true, subtree: true });
  }

  init();
})();